<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostcodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('postcodes')->insert([
            ["postcode"=>8001, "name"=>"Zürich"],
            ["postcode"=>8002, "name"=>"Zürich"],
            ["postcode"=>8003, "name"=>"Zürich"],
            ["postcode"=>8004, "name"=>"Zürich"],
            ["postcode"=>8005, "name"=>"Zürich"],
            ["postcode"=>8006, "name"=>"Zürich"],
            ["postcode"=>8008, "name"=>"Zürich"],
            ["postcode"=>8032, "name"=>"Zürich"],
            ["postcode"=>8037, "name"=>"Zürich"],
            ["postcode"=>8038, "name"=>"Zürich"],
            ["postcode"=>8041, "name"=>"Zürich"],
            ["postcode"=>8044, "name"=>"Dübendorf, Zürich"],
            ["postcode"=>8045, "name"=>"Zürich"],
            ["postcode"=>8046, "name"=>"Zürich"],
            ["postcode"=>8047, "name"=>"Zürich"],
            ["postcode"=>8048, "name"=>"Zürich"],
            ["postcode"=>8049, "name"=>"Zürich"],
            ["postcode"=>8050, "name"=>"Zürich"],
            ["postcode"=>8051, "name"=>"Zürich"],
            ["postcode"=>8052, "name"=>"Zürich"],
            ["postcode"=>8053, "name"=>"Zürich"],
            ["postcode"=>8055, "name"=>"Zürich"],
            ["postcode"=>8057, "name"=>"Zürich"],
            ["postcode"=>8064, "name"=>"Zürich"],
            ["postcode"=>8102, "name"=>"Oberengstringen"],
            ["postcode"=>8103, "name"=>"Unterengstringen"],
            ["postcode"=>8104, "name"=>"Weiningen (ZH)"],
            ["postcode"=>8105, "name"=>"Regensdorf"],
            ["postcode"=>8106, "name"=>"Regensdorf"],
            ["postcode"=>8107, "name"=>"Buchs (ZH)"],
            ["postcode"=>8108, "name"=>"Dällikon"],
            ["postcode"=>8112, "name"=>"Otelfingen"],
            ["postcode"=>8113, "name"=>"Boppelsen"],
            ["postcode"=>8114, "name"=>"Dänikon"],
            ["postcode"=>8115, "name"=>"Hüttikon"],
            ["postcode"=>8117, "name"=>"Fällanden"],
            ["postcode"=>8118, "name"=>"Fällanden"],
            ["postcode"=>8121, "name"=>"Fällanden"],
            ["postcode"=>8122, "name"=>"Maur"],
            ["postcode"=>8123, "name"=>"Maur"],
            ["postcode"=>8124, "name"=>"Maur"],
            ["postcode"=>8125, "name"=>"Zollikon"],
            ["postcode"=>8126, "name"=>"Zumikon"],
            ["postcode"=>8127, "name"=>"Küsnacht (ZH)"],
            ["postcode"=>8132, "name"=>"Egg"],
            ["postcode"=>8133, "name"=>"Egg"],
            ["postcode"=>8134, "name"=>"Adliswil"],
            ["postcode"=>8135, "name"=>"Langnau am Albis, Horgen"],
            ["postcode"=>8136, "name"=>"Thalwil"],
            ["postcode"=>8142, "name"=>"Uitikon"],
            ["postcode"=>8143, "name"=>"Stallikon"],
            ["postcode"=>8152, "name"=>"Opfikon"],
            ["postcode"=>8153, "name"=>"Rümlang"],
            ["postcode"=>8154, "name"=>"Oberglatt"],
            ["postcode"=>8155, "name"=>"Niederhasli"],
            ["postcode"=>8156, "name"=>"Niederhasli"],
            ["postcode"=>8157, "name"=>"Dielsdorf"],
            ["postcode"=>8158, "name"=>"Regensberg"],
            ["postcode"=>8162, "name"=>"Steinmaur"],
            ["postcode"=>8164, "name"=>"Bachs"],
            ["postcode"=>8165, "name"=>"Oberweningen, Schleinikon, Schöfflisdorf"],
            ["postcode"=>8166, "name"=>"Niederweningen"],
            ["postcode"=>8172, "name"=>"Niederglatt"],
            ["postcode"=>8173, "name"=>"Neerach"],
            ["postcode"=>8174, "name"=>"Stadel"],
            ["postcode"=>8175, "name"=>"Stadel"],
            ["postcode"=>8180, "name"=>"Bülach"],
            ["postcode"=>8181, "name"=>"Höri"],
            ["postcode"=>8182, "name"=>"Hochfelden"],
            ["postcode"=>8184, "name"=>"Bachenbülach"],
            ["postcode"=>8185, "name"=>"Winkel"],
            ["postcode"=>8187, "name"=>"Weiach"],
            ["postcode"=>8192, "name"=>"Glattfelden"],
            ["postcode"=>8193, "name"=>"Eglisau"],
            ["postcode"=>8194, "name"=>"Hüntwangen"],
            ["postcode"=>8195, "name"=>"Wasterkingen"],
            ["postcode"=>8196, "name"=>"Wil (ZH)"],
            ["postcode"=>8197, "name"=>"Rafz"],
            ["postcode"=>8245, "name"=>"Feuerthalen"],
            ["postcode"=>8246, "name"=>"Feuerthalen"],
            ["postcode"=>8247, "name"=>"Flurlingen"],
            ["postcode"=>8248, "name"=>"Laufen-Uhwiesen"],
            ["postcode"=>8302, "name"=>"Kloten"],
            ["postcode"=>8303, "name"=>"Bassersdorf"],
            ["postcode"=>8304, "name"=>"Wallisellen"],
            ["postcode"=>8305, "name"=>"Dietlikon"],
            ["postcode"=>8306, "name"=>"Wangen-Brüttisellen"],
            ["postcode"=>8307, "name"=>"Illnau-Effretikon"],
            ["postcode"=>8308, "name"=>"Illnau-Effretikon"],
            ["postcode"=>8309, "name"=>"Nürensdorf"],
            ["postcode"=>8310, "name"=>"Lindau"],
            ["postcode"=>8311, "name"=>"Brütten"],
            ["postcode"=>8312, "name"=>"Lindau"],
            ["postcode"=>8314, "name"=>"Illnau-Effretikon"],
            ["postcode"=>8315, "name"=>"Lindau"],
            ["postcode"=>8317, "name"=>"Lindau"],
            ["postcode"=>8320, "name"=>"Fehraltorf"],
            ["postcode"=>8322, "name"=>"Russikon"],
            ["postcode"=>8330, "name"=>"Pfäffikon"],
            ["postcode"=>8331, "name"=>"Pfäffikon"],
            ["postcode"=>8332, "name"=>"Russikon"],
            ["postcode"=>8335, "name"=>"Hittnau"],
            ["postcode"=>8340, "name"=>"Hinwil"],
            ["postcode"=>8342, "name"=>"Hinwil"],
            ["postcode"=>8344, "name"=>"Bäretswil"],
            ["postcode"=>8345, "name"=>"Bäretswil"],
            ["postcode"=>8352, "name"=>"Elsau, Winterthur"],
            ["postcode"=>8353, "name"=>"Elgg"],
            ["postcode"=>8354, "name"=>"Hofstetten (ZH)"],
            ["postcode"=>8400, "name"=>"Winterthur"],
            ["postcode"=>8404, "name"=>"Winterthur"],
            ["postcode"=>8405, "name"=>"Winterthur"],
            ["postcode"=>8406, "name"=>"Winterthur"],
            ["postcode"=>8408, "name"=>"Winterthur"],
            ["postcode"=>8409, "name"=>"Winterthur"],
            ["postcode"=>8412, "name"=>"Neftenbach"],
            ["postcode"=>8413, "name"=>"Neftenbach"],
            ["postcode"=>8414, "name"=>"Buch am Irchel"],
            ["postcode"=>8415, "name"=>"Berg am Irchel"],
            ["postcode"=>8416, "name"=>"Flaach"],
            ["postcode"=>8418, "name"=>"Schlatt (ZH)"],
            ["postcode"=>8421, "name"=>"Dättlikon"],
            ["postcode"=>8422, "name"=>"Pfungen"],
            ["postcode"=>8424, "name"=>"Embrach"],
            ["postcode"=>8425, "name"=>"Oberembrach"],
            ["postcode"=>8426, "name"=>"Lufingen"],
            ["postcode"=>8427, "name"=>"Freienstein-Teufen, Rorbas"],
            ["postcode"=>8428, "name"=>"Freienstein-Teufen"],
            ["postcode"=>8442, "name"=>"Hettlingen"],
            ["postcode"=>8444, "name"=>"Henggart"],
            ["postcode"=>8447, "name"=>"Dachsen"],
            ["postcode"=>8450, "name"=>"Andelfingen"],
            ["postcode"=>8451, "name"=>"Kleinandelfingen"],
            ["postcode"=>8452, "name"=>"Adlikon"],
            ["postcode"=>8453, "name"=>"Kleinandelfingen"],
            ["postcode"=>8457, "name"=>"Humlikon"],
            ["postcode"=>8458, "name"=>"Dorf"],
            ["postcode"=>8459, "name"=>"Volken"],
            ["postcode"=>8460, "name"=>"Marthalen"],
            ["postcode"=>8461, "name"=>"Kleinandelfingen"],
            ["postcode"=>8462, "name"=>"Rheinau"],
            ["postcode"=>8463, "name"=>"Benken (ZH)"],
            ["postcode"=>8464, "name"=>"Marthalen"],
            ["postcode"=>8465, "name"=>"Trüllikon"],
            ["postcode"=>8466, "name"=>"Trüllikon"],
            ["postcode"=>8467, "name"=>"Truttikon"],
            ["postcode"=>8468, "name"=>"Waltalingen"],
            ["postcode"=>8471, "name"=>"Dägerlen"],
            ["postcode"=>8472, "name"=>"Seuzach"],
            ["postcode"=>8474, "name"=>"Dinhard"],
            ["postcode"=>8475, "name"=>"Ossingen"],
            ["postcode"=>8476, "name"=>"Unterstammheim"],
            ["postcode"=>8477, "name"=>"Oberstammheim"],
            ["postcode"=>8478, "name"=>"Thalheim an der Thur"],
            ["postcode"=>8479, "name"=>"Altikon"],
            ["postcode"=>8482, "name"=>"Winterthur"],
            ["postcode"=>8483, "name"=>"Zell (ZH)"],
            ["postcode"=>8484, "name"=>"Weisslingen"],
            ["postcode"=>8486, "name"=>"Zell (ZH)"],
            ["postcode"=>8487, "name"=>"Zell (ZH)"],
            ["postcode"=>8488, "name"=>"Turbenthal"],
            ["postcode"=>8489, "name"=>"Wildberg"],
            ["postcode"=>8492, "name"=>"Wila"],
            ["postcode"=>8493, "name"=>"Bauma"],
            ["postcode"=>8494, "name"=>"Bauma"],
            ["postcode"=>8495, "name"=>"Turbenthal"],
            ["postcode"=>8496, "name"=>"Fischenthal"],
            ["postcode"=>8497, "name"=>"Fischenthal"],
            ["postcode"=>8498, "name"=>"Fischenthal"],
            ["postcode"=>8499, "name"=>"Bauma"],
            ["postcode"=>8523, "name"=>"Hagenbuch"],
            ["postcode"=>8542, "name"=>"Wiesendangen"],
            ["postcode"=>8543, "name"=>"Wiesendangen"],
            ["postcode"=>8544, "name"=>"Wiesendangen"],
            ["postcode"=>8545, "name"=>"Rickenbach (ZH)"],
            ["postcode"=>8548, "name"=>"Ellikon an der Thur"],
            ["postcode"=>8600, "name"=>"Dübendorf"],
            ["postcode"=>8602, "name"=>"Wangen-Brüttisellen"],
            ["postcode"=>8603, "name"=>"Schwerzenbach"],
            ["postcode"=>8604, "name"=>"Volketswil"],
            ["postcode"=>8605, "name"=>"Volketswil"],
            ["postcode"=>8606, "name"=>"Greifensee, Uster"],
            ["postcode"=>8607, "name"=>"Seegräben"],
            ["postcode"=>8608, "name"=>"Bubikon"],
            ["postcode"=>8610, "name"=>"Uster"],
            ["postcode"=>8614, "name"=>"Gossau (ZH), Uster"],
            ["postcode"=>8615, "name"=>"Uster"],
            ["postcode"=>8616, "name"=>"Uster"],
            ["postcode"=>8617, "name"=>"Mönchaltorf"],
            ["postcode"=>8618, "name"=>"Oetwil am See"],
            ["postcode"=>8620, "name"=>"Wetzikon (ZH)"],
            ["postcode"=>8623, "name"=>"Wetzikon (ZH)"],
            ["postcode"=>8624, "name"=>"Gossau (ZH)"],
            ["postcode"=>8625, "name"=>"Gossau (ZH)"],
            ["postcode"=>8626, "name"=>"Gossau (ZH)"],
            ["postcode"=>8627, "name"=>"Grüningen"],
            ["postcode"=>8630, "name"=>"Rüti (ZH)"],
            ["postcode"=>8632, "name"=>"Dürnten"],
            ["postcode"=>8633, "name"=>"Bubikon"],
            ["postcode"=>8634, "name"=>"Hombrechtikon"],
            ["postcode"=>8635, "name"=>"Dürnten"],
            ["postcode"=>8636, "name"=>"Wald (ZH)"],
            ["postcode"=>8637, "name"=>"Wald (ZH)"],
            ["postcode"=>8700, "name"=>"Küsnacht (ZH)"],
            ["postcode"=>8702, "name"=>"Zollikon"],
            ["postcode"=>8703, "name"=>"Erlenbach (ZH)"],
            ["postcode"=>8704, "name"=>"Herrliberg"],
            ["postcode"=>8706, "name"=>"Meilen"],
            ["postcode"=>8707, "name"=>"Uetikon am See"],
            ["postcode"=>8708, "name"=>"Männedorf"],
            ["postcode"=>8712, "name"=>"Stäfa"],
            ["postcode"=>8713, "name"=>"Stäfa"],
            ["postcode"=>8714, "name"=>"Hombrechtikon"],
            ["postcode"=>8800, "name"=>"Thalwil"],
            ["postcode"=>8802, "name"=>"Kilchberg (ZH)"],
            ["postcode"=>8803, "name"=>"Rüschlikon"],
            ["postcode"=>8804, "name"=>"Wädenswil"],
            ["postcode"=>8805, "name"=>"Richterswil"],
            ["postcode"=>8810, "name"=>"Horgen"],
            ["postcode"=>8815, "name"=>"Horgen"],
            ["postcode"=>8816, "name"=>"Hirzel"],
            ["postcode"=>8820, "name"=>"Wädenswil"],
            ["postcode"=>8824, "name"=>"Schönenberg (ZH)"],
            ["postcode"=>8825, "name"=>"Hütten"],
            ["postcode"=>8833, "name"=>"Richterswil"],
            ["postcode"=>8902, "name"=>"Urdorf"],
            ["postcode"=>8903, "name"=>"Birmensdorf (ZH)"],
            ["postcode"=>8904, "name"=>"Aesch (ZH)"],
            ["postcode"=>8906, "name"=>"Bonstetten"],
            ["postcode"=>8907, "name"=>"Wettswil am Albis"],
            ["postcode"=>8908, "name"=>"Hedingen"],
            ["postcode"=>8909, "name"=>"Affoltern am Albis"],
            ["postcode"=>8910, "name"=>"Affoltern am Albis"],
            ["postcode"=>8911, "name"=>"Rifferswil"],
            ["postcode"=>8912, "name"=>"Obfelden"],
            ["postcode"=>8913, "name"=>"Ottenbach"],
            ["postcode"=>8914, "name"=>"Aeugst am Albis"],
            ["postcode"=>8915, "name"=>"Hausen am Albis"],
            ["postcode"=>8925, "name"=>"Hausen am Albis"],
            ["postcode"=>8926, "name"=>"Kappel am Albis"],
            ["postcode"=>8932, "name"=>"Mettmenstetten"],
            ["postcode"=>8933, "name"=>"Maschwanden"],
            ["postcode"=>8934, "name"=>"Knonau"],
            ["postcode"=>8942, "name"=>"Oberrieden"],
            ["postcode"=>8951, "name"=>"Weiningen (ZH)"],
            ["postcode"=>8952, "name"=>"Schlieren"],
            ["postcode"=>8953, "name"=>"Dietikon"],
            ["postcode"=>8954, "name"=>"Geroldswil"],
            ["postcode"=>8955, "name"=>"Oetwil an der Limmat"]
        ]);
    }
}
